/// Flutter icons InveoxIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InveoxIcons
///      fonts:
///       - asset: fonts/InveoxIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InveoxIcons {
  InveoxIcons._();

  static const _kFontFam = 'InveoxIcons';
  static const String? _kFontPkg = null;

  static const IconData practice = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lab = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
